[[tasks]]
name = "Infrast"
type = "Infrast"
[tasks.params]
#https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/src/MaaCore/Vision/Infrast/InfrastFacilityImageAnalyzer.cpp#L14
# https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/src/MaaWpfGui/Models/AsstTasks/AsstInfrastTask.cs#L102
facility = ["Training", "Trade", "Reception", "Mfg", "Control", "Power", "Office", "Dorm"]
# "_NotUse"、"Money"、"SyntheticJade"、"CombatRecord"、"PureGold"、"OriginStone"、"Chip"
# 交易站 SyntheticJade
drones = "Money"
replenish = true
continue_training = true


[[tasks]]
name = "Mall"
type = "Mall"
[tasks.params]
shopping = true
buy_first = ["招聘许可", "龙门币"]
blacklist = ["加急许可", "家具零件"]
[[tasks.variants]]
condition = { type = "Time", start = "20:00:00" }


[[tasks]]
name = "Recruit"
type = "Recruit"
[tasks.params]
refresh = true
select = [5, 4, 1]
confirm = [5, 4, 3, 1]
[[tasks.variants]]
condition = { type = "Time", start = "16:00:00", end = "20:00:00" }
params = { times = 2, select = [5, 4, 1], confirm = [5, 4, 3, 1] }
[[tasks.variants]]
condition = { type = "Time", start = "04:00:00", end = "12:00:00" }
params = { times = 1, select = [5, 4, 1], confirm = [5, 4, 3, 1] }

[[tasks]]
name = "Award"
type = "Award"
[tasks.params]
award = true
mail = true
recruit = true
orundum = true
mining = true
specialaccess = true
